# Generated by Django 4.0.4 on 2022-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
