# Generated by Django 4.0.4 on 2022-06-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_artwork_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='likes',
        ),
    ]
