# Generated by Django 4.0.4 on 2022-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_artwork_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
